### ISSUE TITLE
snakemake workflow template and python packaging

### ISSUE THREAD

**Issue by fgypas** [snakemake-workflows/snakemake-workflow-template#1]
Hi

I really like the idea of the snakemake-workflows catalog and the current template that allows the workflows to follow a similar file structure.

One issue that I encountered recently, is that the current recommendation contradicts the recommendation for structuring python (PyPi) packages. I would like to continue to follow the same file structure, but at the same time it would be nice to install/package the pipelines via conda/pip. For example doing something like `pip install dna-seq-varlociraptor` would be great. The problem at the moment is that the workflow is at the root directory, so if you install it as a pip package it will appear as `workflow` and will not be under the package name. This would create a conflict if you want to install two pipelines simultaneously.

Also in some cases you might have a wrapper/helper script (for example in python) that is not part of the workflow, but helps you prepare the `samples.tsv` or `config.yaml` files or/and allows you to trigger the pipeline. In such cases you would need to know where the pipeline/Snakefile is located.

So in the current file structure I would additionally have the directories/files in **bold**:
- .github/workflows
- .template
- config
- workflow
- .gitignore
- LICENSE
- README.md
- **scripts**
   - **package-name-prepare-run.py**
   - **package-name-run.py**
- **setup.py**

The `setup.py` normally would be something like:
```
import sys
from setuptools import setup

if sys.version_info < (3, 6):
    sys.exit('Sorry, package-name requires Python >= 3.6')

requirements = [
    "pandas", ...
]

setup(
    name='package-name',
    version='1.0.0',
    description="package-name description",
    url='',
    scripts=['scripts/package-name-prepare-run.py', 'scripts/package-name-run.py'],
    install_requires=requirements,
    keywords='package-name',
    packages=find_packages(include=['workflow']),
    package_data={'pulsar': files},
    include_package_data=True
)
```

In our case the issue would be `packages=find_packages(include=['workflow']),` because in the `site-packages` of the env would appear as `package-name/lib/python3.9/site-packages/workflow` and not as `package-name/lib/python3.9/site-packages/workflow/package-name`.

Do you have any guideline/recommendations on this? Is there an easy way of keeping the current file structure, but at the same having a `setup.py` to install the pipeline properly? I am happy to help if we can expand the snakemake template. Also please let me know if something is not clear.

**Comment by dlaehnemann** [comment]
I have no clue regarding the `setup.py`, as I know too little about using those. So I'll try and point @johanneskoester this way, for your question regarding this.

As to your `scripts` directory, these sound like scripts that could go into the `config/` folder, as they directly pertain to what's happening there. You could then also go and mention and explain their usage in the `config/README.md` that is used for the workflow setup docs in the snakemake workflow catalog. Does that make sense?

**Comment by fgypas** [comment]
Thanks a lot @dlaehnemann . Yes it helps. I add some more content to make it more clear for my current use case and how we could generalise this.

The path of the scripts is not very important. I could move them under config and specify them again as scripts in the `setup` function or even move them within the workflow if it is properly packaged and use an entry point for them:
```
entry_points={
        'console_scripts': ['package-name=workflow:package-name:main'],
    },
```
The important thing for me is that the scripts know where the Snakefile is (or will be) located after the installation, as well as the config files under config.
The reason is that the `package-name-prepare-run.py` will use as template the `config.yaml` to prepare the new run in a separate directory. Then the `package-name-run.py` will find the contents in the generated directory and run the snakemake pipeline. The second script should know where the Snakefile is.

**Comment by dlaehnemann** [comment]
This sounds a bit like your main aim is to reuse the same workflow on different datasets and for that setup, we have started using the mechanism suggested by the snakemake workflow catalog documentation of standardized usage workflows (see for example the [docs for the `dna-seq-varlociraptor` workflow](https://snakemake.github.io/snakemake-workflow-catalog/?usage=snakemake-workflows%2Fdna-seq-varlociraptor). We basically import the whole workflow with the commands described there, which effectively uses [the snakemake module system](https://snakemake.readthedocs.io/en/latest/snakefiles/modularization.html#modules). That way, when you want to update to a newer version of the workflow with bug fixes or added features, you can simply point to a newer release in the `github()` command that looks for the default Snakefile there. And you can adapt things to your dataset at hand in your local Snakefile that does the importing, or even create new `rules/*.smk` files to add functionality, that might later be added back to the main workflow as new functionality. Also, this means you can nicely have a very clean repository for your analysis, that clearly states which version of the workflow you use, but doesn't duplicate all of its code. Instead, your dataset analysis repo mainly contains the configuration of your data (`config/samples.tsv`) and your analysis run (`config/config.yaml`). And you can easily keep that repo private, as the sample description might contain sensitive information, while later easily contributing back newly added rules and functions to the main (public) workflow repo. Does that give you a general idea of how we go about this? And does that maybe sidestep the need for a pip-based deployment system for snakemake workflows?

**Comment by fgypas** [comment]
Thanks. I think that's very useful. I will have a look at `snakedeploy` and the new `modules` features as I have not used them so far.

**Comment by dlaehnemann** [comment]
Also, input on the `snakedeploy` plus `modules` mechanism is very welcome. It's still quite new and while we have had a very intensive round of debugging more than half a year ago, there probably still are bugs around and any ideas to further improve the usability and the respective docs would be great!

**Comment by dlaehnemann** [comment]
Ah, and I'll close this for now, in the hope that these suggestions "solve" your use case. If not, don't hesitate to reopen the issue and keep on asking. I just don't want to forget it and start a list of abandoned issues here...
