### ISSUE TITLE
The workflow defines config file config/config.yaml but it is not present or accessible.

### ISSUE THREAD

**Issue by WanlinLi2021** [snakemake-workflows/snakemake-workflow-template#4]
I tried to apply the strategy used in [snakemake-workflows](https://github.com/snakemake-workflows)/**[rna-seq-star-deseq2](https://github.com/snakemake-workflows/rna-seq-star-deseq2)**. I first stored the **config.yaml** file in the **config** folder, and then referenced this config file in the **Snakefile**.

When I ran `snakemake --cores all`,  the workflow worked fine. However, it does not pass the test in GitHub.

The description of the error received is as follows:
<img width="971" alt="image" src="https://user-images.githubusercontent.com/53668767/215181306-3caa8840-42e7-4899-8d0c-47e8bbb7f55d.png">

I don't know if I've forgotten another important setting. I have tried a lot but failed. Your help would mean a lot to me. Thank you very much.

**Comment by TahiriNadia** [comment]
Now we have found a solution. We forgot to create the .test folder. Now everything works. Thanks!

**Comment by WanlinLi2021** [comment]
Now we have found a solution. We forgot to create the .test folder. Now everything works. Thanks!
